//! Property tests for dependency-reference rewriting and identity preservation.
//!
//! Each case generates a valid roadmap and a fragment from a [`Model`] whose
//! dependency graph is held separately from the rendered text, then applies a
//! structural edit through the CLI and compares the result against the oracle
//! in `tests/support/oracle.rs`. The oracle never parses Markdown and never
//! calls the production clause recognizer, so it can disagree with the product.
//!
//! The properties assert the whole contract at once, per case:
//!
//! - a surviving consumer's clause names its prerequisite's **own** new anchor, never the anchor
//!   some other item inherited;
//! - a clause never carries an anchor a removed identity used to hold;
//! - an edit that would strand a surviving consumer is rejected, and the rejection names an anchor
//!   that really is stranded;
//! - a rejected edit leaves the target byte-identical, terminators included;
//! - unrelated numeric prose, section references, versions, and fenced code examples are not
//!   rewritten.
//!
//! Both supported line endings are generated, singly and in mixed documents.
//! The generator terminates the whole document with one ending, so a mixed
//! document arises from the edit rather than from generation: an item the edit
//! leaves alone keeps its source's terminators while a canonically rendered one
//! comes back as LF. The properties therefore assert dependency identity and
//! unrelated-text preservation across that mix, and assert byte identity after
//! a *rejection* on the raw bytes — the one place where a stray `\r` is a
//! defect rather than a rendering choice.
//!
//! Half of the cases run in place rather than in preview, so the preservation
//! obligation is exercised on the path that actually writes. Preview never
//! opens the target for writing, so a byte-identity assertion there would hold
//! even if rejection normalized terminators on its way to a write.
//!
//! Phase- and step-level renumbering is generated by [`Edit::DeleteStep`] and
//! [`Edit::DeletePhase`], which shift every surviving step and task anchor
//! beneath them.

#[path = "support/dependency_assertions.rs"]
mod dependency_assertions;
#[path = "support/dependency_case.rs"]
mod dependency_case;
#[path = "support/generation.rs"]
mod generation;
#[path = "support/oracle.rs"]
mod oracle;
#[path = "support/rendered_block.rs"]
mod rendered_block;
#[path = "support/workspace.rs"]
mod workspace_support;

use dependency_assertions::{assert_generated_edit, assert_incidental_text_survives};
use dependency_case::{CASES, Mode, build_case};
use oracle::STEP_COUNT;
use proptest::prelude::*;

proptest! {
    #![proptest_config(ProptestConfig {
        cases: CASES,
        .. ProptestConfig::default()
    })]

    #[test]
    fn generated_edits_preserve_dependency_identity(
        step_selectors in prop::collection::vec(any::<u8>(), STEP_COUNT),
        edit_selector in any::<u8>(),
        shape_options in any::<u8>(),
        in_place in any::<bool>(),
        crlf in any::<bool>(),
    ) {
        let case = build_case(&step_selectors, edit_selector, shape_options, crlf)?;
        assert_generated_edit(&case, Mode::from(in_place))?;
    }

    #[test]
    fn generated_edits_never_rewrite_unrelated_numeric_text(
        step_selectors in prop::collection::vec(any::<u8>(), STEP_COUNT),
        edit_selector in any::<u8>(),
        shape_options in any::<u8>(),
        in_place in any::<bool>(),
        crlf in any::<bool>(),
    ) {
        let case = build_case(&step_selectors, edit_selector, shape_options, crlf)?;
        assert_incidental_text_survives(&case, Mode::from(in_place))?;
    }
}
