//! Property tests for dependency-reference rewriting and identity preservation.
//!
//! Each case generates a valid roadmap and a fragment from a [`Model`] whose
//! dependency graph is held separately from the rendered text, then applies a
//! structural edit through the CLI and compares the result against the oracle
//! in `tests/support/oracle.rs`. The oracle never parses Markdown and never
//! calls the production clause recognizer, so it can disagree with the product.
//!
//! The properties assert the whole contract at once, per case:
//!
//! - a surviving consumer's clause names its prerequisite's **own** new anchor, never the anchor
//!   some other item inherited;
//! - a clause never carries an anchor a removed identity used to hold;
//! - an edit that would strand a surviving consumer is rejected, and the rejection names an anchor
//!   that really is stranded;
//! - a rejected edit leaves the target byte-identical;
//! - unrelated numeric prose, section references, versions, and fenced code examples are not
//!   rewritten.
//!
//! Line endings are deliberately LF-only. The parser normalizes CRLF to LF on
//! render, so a CRLF target has no byte-identical round trip to assert and its
//! clause rewriting is already covered by the LF cases at the AST level.
//! Phase- and step-level renumbering is generated by [`Edit::DeleteStep`] and
//! [`Edit::DeletePhase`], which shift every surviving step and task anchor
//! beneath them.

#[path = "support/generation.rs"]
mod generation;
#[path = "support/oracle.rs"]
mod oracle;
#[path = "support/rendered_block.rs"]
mod rendered_block;
#[path = "support/workspace.rs"]
mod workspace_support;

use std::collections::BTreeSet;

use generation::{
    Generated,
    INCIDENTAL_TEXTS,
    Shape,
    fragment_label,
    generate,
    phase_label,
    step_label,
    sub_task_label,
    task_label,
};
use mapsplice::{MapspliceError, parse_cli_request, run_request};
use oracle::{
    Edit,
    Expectation,
    FRAGMENT_BASE,
    ItemId,
    Level,
    Model,
    STEP_COUNT,
    SUB_TASKS_PER_TAIL,
    TASKS_PER_STEP,
    expectation_for,
};
use proptest::{prelude::*, test_runner::TestCaseResult};
use rendered_block::{item_block, strip_fenced_regions};
use workspace_support::{Workspace, create_workspace};

/// One generated case: the edit, the documents, and the expected outcome.
struct Case {
    edit: Edit,
    generated: Generated,
    expectation: Expectation,
}

/// Property cases are slow enough that a modest count exercises them well.
const CASES: u32 = 256;

proptest! {
    #![proptest_config(ProptestConfig {
        cases: CASES,
        .. ProptestConfig::default()
    })]

    #[test]
    fn generated_edits_preserve_dependency_identity(
        step_selectors in prop::collection::vec(any::<u8>(), STEP_COUNT),
        edit_selector in any::<u8>(),
        shape_options in any::<u8>(),
    ) {
        let case = build_case(&step_selectors, edit_selector, shape_options)?;
        assert_generated_edit(&case)?;
    }

    #[test]
    fn generated_edits_never_rewrite_unrelated_numeric_text(
        step_selectors in prop::collection::vec(any::<u8>(), STEP_COUNT),
        edit_selector in any::<u8>(),
        shape_options in any::<u8>(),
    ) {
        let case = build_case(&step_selectors, edit_selector, shape_options)?;
        assert_incidental_text_survives(&case)?;
    }
}

/// Build one generated case from the supplied selectors.
fn build_case(
    step_selectors: &[u8],
    edit_selector: u8,
    shape_options: u8,
) -> Result<Case, TestCaseError> {
    let shape = Shape {
        options: shape_options,
    };
    let generated =
        generate(step_selectors, shape).map_err(|error| TestCaseError::fail(error.to_string()))?;
    let edit = Edit::from_selector(edit_selector);
    let expectation = expectation_for(&generated.model, edit);
    Ok(Case {
        edit,
        generated,
        expectation,
    })
}

/// Assert that one generated edit matches its independently computed outcome.
fn assert_generated_edit(case: &Case) -> TestCaseResult {
    let workspace = prepare_workspace(case)?;

    match (&case.expectation, run_case(&workspace, case)) {
        (Expectation::Reject { stalled }, Err(MapspliceError::DanglingDependency { anchor })) => {
            prop_assert!(
                stalled.contains(&anchor.to_string()),
                "rejection must name a stranded anchor; named `{anchor}`, stranded {stalled:?}",
            );
            assert_target_unchanged(&workspace, &case.generated.target)?;
        }
        (Expectation::Reject { stalled }, Err(other)) => {
            prop_assert!(
                false,
                "expected a dangling-dependency rejection naming one of {stalled:?}, got `{other}`",
            );
        }
        (Expectation::Reject { stalled }, Ok(_)) => {
            prop_assert!(
                false,
                "edit must be rejected: surviving consumers still require {stalled:?}",
            );
        }
        (Expectation::Accept { .. }, Err(error)) => {
            prop_assert!(false, "edit must succeed, but failed with `{error}`");
        }
        (Expectation::Accept { .. }, Ok(rendered)) => {
            assert_accepted(&rendered, case)?;
        }
    }
    Ok(())
}

/// Assert a successful edit renders exactly the anchors the oracle predicts.
///
/// Every assertion is scoped to the block the owning item renders, not to the
/// whole document. A document-wide `contains` would be satisfied by another
/// item's text, and in particular by the fenced code example the generator
/// emits into every task body spelling `Requires 1.1.1.`, which would make a
/// clause assertion for that anchor vacuous.
fn assert_accepted(rendered: &str, case: &Case) -> TestCaseResult {
    let Some(anchors) = case.expectation.anchors() else {
        prop_assert!(false, "accepted case must carry expected anchors");
        return Ok(());
    };
    let retired = case.expectation.retired().cloned().unwrap_or_default();

    for (identity, anchor) in anchors {
        if identity.is_fragment() {
            continue;
        }
        let stem = item_stem(*identity);
        let Some(block) = item_block(rendered, &stem) else {
            prop_assert!(
                false,
                "surviving identity {identity:?} must render a summary containing \
                 `{stem}`\nrendered:\n{rendered}",
            );
            return Ok(());
        };
        let expected = format!("{anchor}. {stem}");
        prop_assert!(
            block.contains(&expected),
            "surviving identity {identity:?} must render as `{expected}`\nblock:\n{block}",
        );
    }

    for (consumer, prerequisite, expected_anchor) in case.expectation.rewritten() {
        let Some(block) = item_block(rendered, &item_stem(*consumer)) else {
            prop_assert!(
                false,
                "consumer {consumer:?} must render a summary to carry a clause",
            );
            return Ok(());
        };
        let clause = format!("Requires {expected_anchor}.");
        prop_assert!(
            block.contains(&clause),
            "consumer {consumer:?} must carry a clause `{clause}` for \
             {prerequisite:?}\nblock:\n{block}",
        );
        assert_clause_is_not_incidental(block, &clause, *consumer)?;
    }

    assert_no_retired_clause(rendered, &retired, case)?;
    Ok(())
}

/// Assert the clause appears outside the item's fenced code examples.
///
/// The generator writes a fenced block whose content is itself clause-shaped,
/// so `block.contains(clause)` alone cannot distinguish a real clause from that
/// example. Removing the fenced regions first is what makes the assertion bite.
fn assert_clause_is_not_incidental(block: &str, clause: &str, consumer: ItemId) -> TestCaseResult {
    let outside_fences = strip_fenced_regions(block);
    prop_assert!(
        outside_fences.contains(clause),
        "consumer {consumer:?} must carry `{clause}` outside its fenced code examples; the only \
         occurrence was inside one\nblock:\n{block}",
    );
    Ok(())
}

/// Assert no rewritten clause points at an anchor a removed identity vacated.
///
/// This is the identity-preservation obligation in observable form: a clause
/// reading a retired anchor would mean a consumer had silently resolved to a
/// different item that inherited the old number.
fn assert_no_retired_clause(
    rendered: &str,
    retired: &BTreeSet<String>,
    case: &Case,
) -> TestCaseResult {
    let live_anchors = case
        .expectation
        .anchors()
        .map(|anchors| anchors.values().cloned().collect::<BTreeSet<_>>())
        .unwrap_or_default();

    for anchor in retired {
        if live_anchors.contains(anchor) {
            continue;
        }
        for spelling in clause_spellings(rendered, anchor) {
            prop_assert!(
                !rendered.contains(&spelling),
                "retired anchor `{anchor}` must not survive in `{spelling}`\nrendered:\n{rendered}",
            );
        }
    }
    Ok(())
}

/// Return every clause spelling that names `anchor`, in a blind scan.
///
/// The scan is deliberately naive and does not reuse the production clause
/// recognizer: it splits on whitespace and reports tokens whose punctuation
/// stripped equals the anchor. A false positive is resolved by the caller
/// checking whether the anchor is live, so the scan can afford to be coarse.
fn clause_spellings(rendered: &str, anchor: &str) -> Vec<String> {
    let with_dot = format!("{anchor}.");
    rendered
        .split_whitespace()
        .filter(|token| token.trim_matches(['-', '*', '`']) == with_dot)
        .map(|_| format!("Requires {anchor}."))
        .collect()
}

/// Assert unrelated numeric text is preserved verbatim, whatever the outcome.
///
/// Each task's incidental prose and fenced example are checked inside that
/// task's own block, so a surviving stray copy elsewhere in the document
/// cannot satisfy the assertion. A delete whose anchor precedes a task
/// legitimately removes that task's block, so only blocks still present are
/// inspected.
fn assert_incidental_text_survives(case: &Case) -> TestCaseResult {
    let workspace = prepare_workspace(case)?;

    let Ok(rendered) = run_case(&workspace, case) else {
        assert_target_unchanged(&workspace, &case.generated.target)?;
        return Ok(());
    };

    let mut inspected = 0_usize;
    for identity in Model::per_task_identities() {
        if identity.is_fragment() {
            continue;
        }
        let Some(block) = item_block(&rendered, &item_stem(identity)) else {
            continue;
        };
        inspected += 1;
        for fragment in &INCIDENTAL_TEXTS[..3] {
            prop_assert!(
                block.contains(fragment),
                "incidental text `{fragment}` must survive inside {identity:?}'s \
                 block\nblock:\n{block}",
            );
        }
        prop_assert!(
            block.contains("```text\n  Requires 1.1.1.\n  ```"),
            "task {identity:?} must keep its fenced example untouched\nblock:\n{block}",
        );
    }
    prop_assert!(
        inspected > 0,
        "at least one task block must survive to inspect\nrendered:\n{rendered}",
    );
    Ok(())
}

/// Return the summary stem the generator renders for one identity.
fn item_stem(identity: ItemId) -> String {
    match identity.level {
        Level::Phase => phase_label(identity.index),
        Level::Step => step_label(identity.index),
        Level::Task if identity.is_fragment() => fragment_label(identity.index - FRAGMENT_BASE),
        Level::Task => task_label(identity.index),
        Level::SubTask => sub_task_label(
            identity.index.div_euclid(SUB_TASKS_PER_TAIL) * TASKS_PER_STEP + TASKS_PER_STEP - 1,
            identity.index.rem_euclid(SUB_TASKS_PER_TAIL),
        ),
    }
}

/// Run the generated edit through the CLI, returning rendered stdout on success.
///
/// The request is built and run in process: a rejected edit must never reach
/// the filesystem, and the in-process path lets the test inspect the target
/// afterwards without a shell.
fn run_case(workspace: &Workspace, case: &Case) -> Result<String, MapspliceError> {
    let mut args = vec!["mapsplice".to_owned()];
    match case.edit {
        Edit::InsertTasksBefore { .. } => {
            args.push("insert".to_owned());
            args.push(workspace.target.to_string());
            args.push(case.edit.anchor());
            args.push(workspace.fragment.to_string());
        }
        Edit::ReplaceTask { .. } => {
            args.push("replace".to_owned());
            args.push(workspace.target.to_string());
            args.push(case.edit.anchor());
            args.push(workspace.fragment.to_string());
        }
        Edit::DeleteTask { .. } | Edit::DeleteStep { .. } | Edit::DeletePhase { .. } => {
            args.push("delete".to_owned());
            args.push(workspace.target.to_string());
            args.push(case.edit.anchor());
        }
    }
    let request = parse_cli_request(args)?;
    run_request(request).map(|outcome| outcome.stdout.unwrap_or_default())
}

/// Write the generated target and fragment into a fresh workspace.
///
/// Helpers propagate with `?` rather than `expect`, because Clippy's
/// `expect_used` is denied and `allow-expect-in-tests` covers only the
/// `#[test]` bodies themselves, not the helpers they call.
fn prepare_workspace(case: &Case) -> Result<Workspace, TestCaseError> {
    let workspace = create_workspace().map_err(|error| TestCaseError::fail(error.to_string()))?;
    workspace
        .write_target(&case.generated.target)
        .map_err(|error| TestCaseError::fail(error.to_string()))?;
    workspace
        .write_fragment(&case.generated.fragment)
        .map_err(|error| TestCaseError::fail(error.to_string()))?;
    Ok(workspace)
}

/// Assert the target file still holds exactly the generated bytes.
fn assert_target_unchanged(workspace: &Workspace, expected: &str) -> TestCaseResult {
    let after = workspace
        .dir
        .read_to_string("target.md")
        .map_err(|error| TestCaseError::fail(error.to_string()))?;
    prop_assert!(
        after == expected,
        "target must be left byte-identical\nexpected:\n{expected}\ngot:\n{after}",
    );
    Ok(())
}
